### PR TITLE
use array_map instead of call_user_func

### PR DESCRIPTION
**Pull request by stamster**
no foreach(), no call_user_func() example.

### CODE REVIEW

**Review by briancvn — COMMENTED** [review]
Hi Stamster
Thanks for your help, but i'm not sure it array_map work with function have more than 1 param pass. How do you thing about that ?

**Comment by stamster** [comment]
You mean this:
```php
array_map([$executable, 'run'], $args);
```
?
That surely works - regular syntax for callable in PHP - pass object instance and method name as a string in array.

**Comment by briancvn** [comment]
Hi Stamster
We need to call method __run__ 1 time withh 3 params ($args) pass. If you use __array_map([$executable, 'run'], $args);__ it will be call method run 3 times with 1 param pass. So it wrong expected of method call. And __array_map__ is method creates a new array with the results of calling a provided function on every element in the calling array, it inappropriate in this case.

**Comment by stamster** [comment]
Ah, I see. Well, then only outer `foreach()` can be replaced with `array_map`, whilst inner         `call_user_func_array([$executable, 'run'], $args); ` will be left intact.

> And array_map is method creates a new array with the results of calling a provided function on every element in the calling array, it inappropriate in this case.

that does not really matter, if you needed to initiate callback on every member of array (e.g. do some processing).

In your original code with `call_user_func_array` you do exactly that, call the callback.

**Comment by azjezz** [comment]
i think its possible to get rid of `call_user_fun_array` completely  like this : 

```php
        array_map(function (BootstrapInterface $executable = null) use ($args) {
            ([$executable, 'run'])(...$args);
        }
```

**Comment by stamster** [comment]
@azjezz well that triggers 'run' method found on a given object only once, whilst we expect that each array member from `$args` will be iterated over. So you actually need `array_map()` in order to iterate over `$args `. 

OR that is exactly what @briancvn expects? Now I'm not sure.


Thus my 1st commit here:
https://github.com/briancvn/cms-3.0/pull/1/commits/ff823df99967c9adac99cac0c284e864dd044c91

looks like it shall work, I haven't tested so I accepted @briancvn comment that it will cause unexpected behavior, but now I believe it will work - it only needs test.



```php
array_map([myObjInstance(), 'setOrDoSomething'], $set_parts);
```

Where:
`myObjInstance()` will return object.
`setOrDoSomething` is a visible method from a given object.
`$set_parts` is a plain numeric array.

This is now fun, @briancvn if you have the nerves to use code from my 1st commit https://github.com/briancvn/cms-3.0/pull/1/commits/ff823df99967c9adac99cac0c284e864dd044c91 and try entire CMS. I believe it shall work.

**Comment by stamster** [comment]
OKi, I just tested and concluded that both of the following yields same results:


```php
([myObjInstance(), 'setOrDoSomething'])(...$set_parts);
```

```php
myObjInstance()->setOrDoSomething(...$set_parts);
//or usual instance
$myObjInstance->setOrDoSomething(...$set_parts);
```

@azjezz you only need to modify target method to accept variadic function token.

So in my case:
```php
function setOrDoSomething(...$args){}
```

So I guess that is solution which @briancvn expected.

**Comment by azjezz** [comment]
i didn't mean we shall do this : 
```php
 array_map([$this->_executables,'run'],$args);
```
but instead this : 
```php
 array_map(function (BootstrapInterface $executable = null) use ($args) {
            ([$executable,'run'])(...$args); // same as calling call_user_func_array
 }, $this->_executables);
```
which have the same result, without having to call `call_user_func_array`.
example : 
https://3v4l.org/Wr7lr
using `call_user_func_array` : 
https://3v4l.org/fgMqF

**Comment by stamster** [comment]
@azjezz I have corrected my post in the next one, in case you missed it. Your proposed syntax does work, we only need to modify target method to accept variadic function token.

**Pull request merged**
